import 'package:flutter/material.dart';

ThemeData pinkTheme = ThemeData(
  colorScheme: const ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xFFE91E63),
    surfaceTint: Color(0xFFE91E63),
    onPrimary: Color(0xFFFFFFFF),
    primaryContainer: Color(0xFFFFC1E3),
    onPrimaryContainer: Color(0xFFC2185B),
    secondary: Color(0xFFF06292),
    onSecondary: Color(0xFFFFFFFF),
    secondaryContainer: Color(0xFFF8BBD0),
    onSecondaryContainer: Color(0xFF880E4F),
    tertiary: Color(0xFFEC407A),
    onTertiary: Color(0xFFFFFFFF),
    tertiaryContainer: Color(0xFFFF80AB),
    onTertiaryContainer: Color(0xFFD81B60),
    error: Color(0xFFD50000),
    onError: Color(0xFFFFFFFF),
    errorContainer: Color(0xFFFF8A80),
    onErrorContainer: Color(0xFFB71C1C),
    surface: Color(0xFFFFEBEE),
    onSurface: Color(0xFF212121),
    onSurfaceVariant: Color(0xFF757575),
    outline: Color(0xFFBDBDBD),
    outlineVariant: Color(0xFFE0E0E0),
    shadow: Color(0xFF000000),
    scrim: Color(0xFF000000),
    inverseSurface: Color(0xFF424242),
    inversePrimary: Color(0xFFF8BBD0),
    primaryFixed: Color(0xFF880E4F),
    onPrimaryFixed: Color(0xFFFFC1E3),
    primaryFixedDim: Color(0xFFD81B60),
    onPrimaryFixedVariant: Color(0xFFEC407A),
    secondaryFixed: Color(0xFFEC407A),
    onSecondaryFixed: Color(0xFFFF80AB),
    secondaryFixedDim: Color(0xFFE91E63),
    onSecondaryFixedVariant: Color(0xFF880E4F),
    tertiaryFixed: Color(0xFFEC407A),
    onTertiaryFixed: Color(0xFFFF80AB),
    tertiaryFixedDim: Color(0xFFD81B60),
    onTertiaryFixedVariant: Color(0xFFF8BBD0),
    surfaceDim: Color(0xFFFFEBEE),
    surfaceBright: Color(0xFFFCE4EC),
    surfaceContainerLowest: Color(0xFFFFC1E3),
    surfaceContainerLow: Color(0xFFFFCDD2),
    surfaceContainer: Color(0xFFF8BBD0),
    surfaceContainerHigh: Color(0xFFF48FB1),
    surfaceContainerHighest: Color(0xFFE91E63),
  ),
);
